name: nf-core aws test
# This workflow is triggered on pushes and PRs to the master branch.
# It runs the -profile 'test' on AWS batch
on:
  push:
  pull_request:
    branches:
      - master
      - dev
  release:
    types: [published]

jobs:
    run-awstest:
        runs-on: ubuntu-latest
        if: github.repository == 'nf-core/awsmegatests'
        steps:
        - uses: goanpeca/setup-miniconda@v1
          with:
            auto-update-conda: true
            python-version: ${{ matrix.python-version }}
        - name: Install aws client
          run: conda install -c conda-forge awscli
        - name: Start AWS batch job
          env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWSTEST_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWSTEST_KEY_SECRET }}
            TOWER_ACCESS_TOKEN: ${{ secrets.AWSTEST_TOWER_TOKEN }}
            AWS_JOB_DEFINITION: ${{ secrets.AWS_JOB_DEFINITION }}
            AWS_JOB_QUEUE: ${{ secrets.AWS_JOB_QUEUE }}
            AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          run: |
            aws batch submit-job \
            --region eu-west-1 \
            --job-name nf-core-awstest \
            --job-queue '${AWS_JOB_QUEUE}' \
            --job-definition '${AWS_JOB_DEFINITION}' \
            --container-overrides '{"command": ["nf-core/rnaseq", "-r dev -profile test --outdir s3://'"${AWS_S3_BUCKET}"'/awsmegatests/results_'"${GITHUB_SHA}"' -w s3://'"${AWS_S3_BUCKET}"'/awsmegatests/work_'"${GITHUB_SHA}"' -with-tower"],"environment": [{"name": "TOWER_ACCESS_TOKEN","value": "'"$TOWER_ACCESS_TOKEN"'"}]}'


